-- =====================================================================
-- FINTECH - Script de criacao das tabelas
-- Executar no SQL Developer, na instancia Oracle da FIAP,
-- ANTES de rodar a classe fintech.Teste.
-- =====================================================================

-- Remove as tabelas caso ja existam (ignore os erros na 1a execucao)
DROP TABLE T_TRANSACAO CASCADE CONSTRAINTS;
DROP TABLE T_CONTA     CASCADE CONSTRAINTS;
DROP TABLE T_CLIENTE   CASCADE CONSTRAINTS;

-- Cliente (titular das contas)
CREATE TABLE T_CLIENTE (
    ID_CLIENTE      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NM_CLIENTE      VARCHAR2(100) NOT NULL,
    NR_CPF          CHAR(11)      NOT NULL,
    DS_EMAIL        VARCHAR2(120) NOT NULL,
    NR_TELEFONE     VARCHAR2(20)  NOT NULL,
    NR_IDADE        NUMBER(3)     NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT CK_CLIENTE_IDADE CHECK (NR_IDADE >= 18)
);

-- Conta (Conta Corrente e Conta Poupanca na mesma tabela, identificadas por TP_CONTA)
CREATE TABLE T_CONTA (
    ID_CONTA              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_CLIENTE            NUMBER        NOT NULL,
    TP_CONTA              VARCHAR2(8)   NOT NULL,
    NR_CONTA              VARCHAR2(10)  NOT NULL,
    NR_AGENCIA            VARCHAR2(4)   NOT NULL,
    VL_SALDO              NUMBER(12,2)  NOT NULL,
    ST_ATIVA              CHAR(1)       DEFAULT 'S' NOT NULL,
    -- colunas da Conta Corrente
    VL_LIMITE_CHEQUE      NUMBER(12,2),
    VL_TAXA_MANUTENCAO    NUMBER(8,2),
    -- colunas da Conta Poupanca
    TX_RENDIMENTO_MENSAL  NUMBER(6,4),
    NR_DIA_ANIVERSARIO    NUMBER(2),
    CONSTRAINT PK_CONTA PRIMARY KEY (ID_CONTA),
    CONSTRAINT FK_CONTA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES T_CLIENTE (ID_CLIENTE),
    CONSTRAINT CK_CONTA_TIPO CHECK (TP_CONTA IN ('CORRENTE', 'POUPANCA')),
    CONSTRAINT CK_CONTA_ATIVA CHECK (ST_ATIVA IN ('S', 'N'))
);

-- Transacao (extrato de cada conta)
CREATE TABLE T_TRANSACAO (
    ID_TRANSACAO          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_CONTA              NUMBER        NOT NULL,
    TP_TRANSACAO          VARCHAR2(30)  NOT NULL,
    VL_TRANSACAO          NUMBER(12,2)  NOT NULL,
    DS_TRANSACAO          VARCHAR2(150) NOT NULL,
    DT_TRANSACAO          TIMESTAMP     NOT NULL,
    VL_SALDO_RESULTANTE   NUMBER(12,2)  NOT NULL,
    CONSTRAINT PK_TRANSACAO PRIMARY KEY (ID_TRANSACAO),
    CONSTRAINT FK_TRANSACAO_CONTA FOREIGN KEY (ID_CONTA) REFERENCES T_CONTA (ID_CONTA),
    CONSTRAINT CK_TRANSACAO_VALOR CHECK (VL_TRANSACAO > 0)
);
